### ISSUE TITLE
Node stopping synchronization after some time

### ISSUE THREAD

**Issue by khelle** [NemProject/nem.core#18]
Hi, 
I dont know where to put feedback regarding the bug using NEM full-node, so I decided to write here. My problem is that, after some time the full-node stops synchronizing. The restart helps, but if I do not restart the process it is stuck. When I look into logs I see following exception being thrown:

```
Dec 23 10:06:42 localhost nix.runNis.sh[10824]: 2017-12-23 09:06:42.637 WARNING forcibly aborting request to http://nijuichi.nem.ninja:7890/chain/score (org.nem.core.connect.HttpMethodClient lambda$sendRequest$2)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]: 2017-12-23 09:06:42.637 WARNING Timer SYNC raised exception: java.util.concurrent.CancellationException
Dec 23 10:06:42 localhost nix.runNis.sh[10824]: java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2265)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.cancelled(HttpMethodClient.java:216)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:157)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionCancelled(DefaultClientExchangeHandlerImpl.java:112)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.cancel(AbstractClientExchangeHandler.java:432)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.apache.http.client.methods.AbstractExecutionAwareRequest.abort(AbstractExecutionAwareRequest.java:90)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.nem.core.connect.HttpMethodClient.lambda$sendRequest$2(HttpMethodClient.java:129)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at org.nem.core.async.SleepFuture$1.run(SleepFuture.java:24)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.TimerThread.mainLoop(Timer.java:555)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.TimerThread.run(Timer.java:505)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]: Caused by: java.util.concurrent.CancellationException
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:         ... 14 more
Dec 23 10:06:42 localhost nix.runNis.sh[10824]:  (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)
Dec 23 10:06:44 localhost nix.runNis.sh[10824]: 2017-12-23 09:06:44.344 INFO calculating trust values (org.nem.peer.trust.CachedTrustProvider a)
Dec 23 10:06:44 localhost nix.runNis.sh[10824]: 2017-12-23 09:06:44.344 INFO trust calculation finished (1 values) (org.nem.peer.trust.CachedTrustProvider a)
```

How can I fix that?

**Comment by Crypto2** [comment]
We are having similar problems, usually restarting multiple times daily.Needless to say the users don't appreciate it. We are using the latest official version from the website, 0.6.93. I see a 0.6.95 at http://bob.nem.ninja/ but don't know if it's production ready or beta and would fix this or not?
