### ISSUE TITLE
Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by zhp1254** [NemProject/nem.core#33]
**### node: nis-0.6.96.tgz**

2018-11-27 07:45:40.759 INFO synchronizing with Node [Hi, I am Alice5 <NCL63DFN3TD5RUDVEMPTHSAUHZFDCTXFOW6KFV7J>] @ [108.61.182.27] (org.nem.peer.services.NodeSynchronizer b)
2018-11-27 07:45:41.017 WARNING Timer SYNC raised exception: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at org.nem.core.connect.HttpMethodClient.sendRequest(HttpMethodClient.java:118)
        at org.nem.core.connect.HttpMethodClient.post(HttpMethodClient.java:89)
        at org.nem.peer.connect.HttpCommunicator.a(HttpCommunicator.java:37)
        at org.nem.nis.connect.AuditedCommunicator.a(AuditedCommunicator.java:31)
        at org.nem.nis.sz.uht.a(HttpConnector.java:145)
        at org.nem.nis.sz.uht.a(HttpConnector.java:157)
        at org.nem.nis.sz.uht.i(HttpConnector.java:110)
        at org.nem.nis.pz.mtf.fG(RemoteBlockLookupAdapter.java:29)
        at org.nem.nis.sync.BlockChainComparer$Impl.fr(BlockChainComparer.java:94)
        at org.nem.nis.sync.BlockChainComparer$Impl.fp(BlockChainComparer.java:60)
        at org.nem.nis.sync.BlockChainComparer.a(BlockChainComparer.java:32)
        at org.nem.nis.sync.BlockChainUpdater.a(BlockChainUpdater.java:148)
        at org.nem.nis.sync.BlockChainUpdater.c(BlockChainUpdater.java:83)
        at org.nem.nis.BlockChain.b(BlockChain.java:112)
        at org.nem.nis.BlockChain.a(BlockChain.java:104)
        at org.nem.nis.tae.a(CountingBlockSynchronizer.java:39)
        at org.nem.peer.services.NodeSynchronizer.b(NodeSynchronizer.java:50)
        at org.nem.peer.PeerNetwork.gt(PeerNetwork.java:141)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        ... 3 more

**Comment by zhangyanhuivv** [comment]
hi, Has the problem been solved? I also have this problem.

**Comment by zhangyanhuivv** [comment]
Hi zhp:
If you have started NIS with only 1GB heap. May you can adjust the startup param to give java more heap. Since it is a 4GB node, you can give 2800M to the java process.

**Comment by shabbir-bblab** [comment]
Hello, I'm running into same issue and still no answer....I tried @zhangyanhuivv 's solution but it didn't work. 
Please provide answer of this issue.

**Comment by zhp1254** [comment]
use nis-0.6.95.tgz solved this

**Comment by chelpurirajashekaer** [comment]
@zhp1254 
Hi, Can you explain it a bit more? I am also facing the same problem
