### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by zhp1254** [NemProject/nem.core#35]
version:6.95

(org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)
2018-11-30 03:31:15.695 INFO Updating "Node [[c=#e1a92b]Hello,[/c] [c=#41ce7c]Alice.[/c] [c=#8e8e8e]I love you.[/c] <NBJGEMONTWT345ABUGYAL6TH4ZLI4FXK4VM3AMDI>] @ [149.28.44.45]" -> ACTIVE (org.nem.peer.services.NodeRefresher update)
2018-11-30 03:31:28.662 WARNING Timer SYNC raised exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
 (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)

**Comment by ichuan** [comment]
> version:6.95
> 
> (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)
> 2018-11-30 03:31:15.695 INFO Updating "Node [[c=#e1a92b]Hello,[/c] [c=#41ce7c]Alice.[/c] [c=#8e8e8e]I love you.[/c] ] @ [149.28.44.45]" -> ACTIVE (org.nem.peer.services.NodeRefresher update)
> 2018-11-30 03:31:28.662 WARNING Timer SYNC raised exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
> java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: GC overhead limit exceeded
> at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
> at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
> (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)

Same problem here, resolved by increasing java memory limit to 1G ~ 2G (originally 512M ~ 1G):
```
# nix.runNis.sh
java -Xms1G -Xmx2G -cp .:./*:../libs/* org.nem.deploy.CommonStarter
```

**Comment by BloodyRookie** [comment]
i recommend 4G at the moment when running a full node
