### ISSUE TITLE
Timer CHECKING CHAIN SYNCHRONIZATION raised exception during start: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by boy-good** [NemProject/nem.core#41]
2019-07-18 05:33:22.310 INFO synchronizing with Node [[c=#86c0e9]nijuichi[/c] <NCZ6YBREMON6BP5X4M7KOMKPV6JW6YY2SHB3RJ7D>] @ [nijuichi.nem.ninja] (org.nem.peer.services.NodeSynchronizer b)
2019-07-18 05:33:22.717 WARNING Timer SYNC raised exception: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at org.nem.core.connect.HttpMethodClient.sendRequest(HttpMethodClient.java:118)
        at org.nem.core.connect.HttpMethodClient.post(HttpMethodClient.java:89)
        at org.nem.peer.connect.HttpCommunicator.a(HttpCommunicator.java:37)
        at org.nem.nis.connect.AuditedCommunicator.a(AuditedCommunicator.java:31)
        at org.nem.nis.sz.uht.a(HttpConnector.java:145)
        at org.nem.nis.sz.uht.a(HttpConnector.java:157)
        at org.nem.nis.sz.uht.i(HttpConnector.java:110)
        at org.nem.nis.pz.mtf.fG(RemoteBlockLookupAdapter.java:29)
        at org.nem.nis.sync.BlockChainComparer$Impl.fr(BlockChainComparer.java:94)
        at org.nem.nis.sync.BlockChainComparer$Impl.fp(BlockChainComparer.java:60)
        at org.nem.nis.sync.BlockChainComparer.a(BlockChainComparer.java:32)
        at org.nem.nis.sync.BlockChainUpdater.a(BlockChainUpdater.java:148)
        at org.nem.nis.sync.BlockChainUpdater.c(BlockChainUpdater.java:83)
        at org.nem.nis.BlockChain.b(BlockChain.java:112)
        at org.nem.nis.BlockChain.a(BlockChain.java:104)
        at org.nem.nis.tae.a(CountingBlockSynchronizer.java:39)
        at org.nem.peer.services.NodeSynchronizer.b(NodeSynchronizer.java:50)
        at org.nem.peer.PeerNetwork.gt(PeerNetwork.java:141)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        ... 3 more
 (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/61435483-1d51b680-a96b-11e9-824c-1c22495a2e0c.png)
what it mean？

**Comment by boy-good** [comment]
2019-07-19 07:44:05.368 WARNING Timer SYNC raised exception: java.util.concurrent.CancellationException
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2265)
        at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.cancelled(HttpMethodClient.java:216)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:157)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionCancelled(DefaultClientExchangeHandlerImpl.java:116)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestCancelled(AbstractClientExchangeHandler.java:357)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$200(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.cancelled(AbstractClientExchangeHandler.java:397)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.cancelled(PoolingNHttpClientConnectionManager.java:295)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$2.cancel(PoolingNHttpClientConnectionManager.java:304)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.cancel(AbstractClientExchangeHandler.java:443)
        at org.apache.http.client.methods.AbstractExecutionAwareRequest.abort(AbstractExecutionAwareRequest.java:90)
        at org.nem.core.connect.HttpMethodClient.lambda$sendRequest$2(HttpMethodClient.java:129)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at org.nem.core.async.SleepFuture$1.run(SleepFuture.java:24)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.util.concurrent.CancellationException
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
        ... 21 more
 (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)

**Comment by harryweiyongjie** [comment]
> 2019-07-19 07:44:05.368 WARNING Timer SYNC raised exception: java.util.concurrent.CancellationException
> java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
> at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
> at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
> at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
> at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
> at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
> at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2265)
> at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.cancelled(HttpMethodClient.java:216)
> at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
> at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:157)
> at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionCancelled(DefaultClientExchangeHandlerImpl.java:116)
> at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestCancelled(AbstractClientExchangeHandler.java:357)
> at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$200(AbstractClientExchangeHandler.java:62)
> at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.cancelled(AbstractClientExchangeHandler.java:397)
> at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
> at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.cancelled(PoolingNHttpClientConnectionManager.java:295)
> at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
> at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$2.cancel(PoolingNHttpClientConnectionManager.java:304)
> at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.cancel(AbstractClientExchangeHandler.java:443)
> at org.apache.http.client.methods.AbstractExecutionAwareRequest.abort(AbstractExecutionAwareRequest.java:90)
> at org.nem.core.connect.HttpMethodClient.lambda$sendRequest$2(HttpMethodClient.java:129)
> at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
> at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
> at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
> at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
> at org.nem.core.async.SleepFuture$1.run(SleepFuture.java:24)
> at java.util.TimerThread.mainLoop(Timer.java:555)
> at java.util.TimerThread.run(Timer.java:505)
> Caused by: java.util.concurrent.CancellationException
> at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
> ... 21 more
> (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)

@boy-good hey，do you solve this problem? I almost have the same problem like you, and I use the newest NIS node version 0.6.97. I see the previous post says one person use 0.6.95 version solve this problem.
