### ISSUE TITLE
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException

### ISSUE THREAD

**Issue by sweetpotatoz** [NemProject/nem.core#42]
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

NIS version: 0.6.97 BETA

```
2019-10-19 00:40:00.590 WARNING forcibly aborting request to http://108.61.168.86:7890/push/transactions (org.nem.core.connect.HttpMethodClient lambda$sendRequest$2)
2019-10-19 00:40:00.590 WARNING forcibly aborting request to http://62.75.163.236:7890/push/transactions (org.nem.core.connect.HttpMethodClient lambda$sendRequest$2)
2019-10-19 00:40:00.590 WARNING forcibly aborting request to http://san.nem.ninja:7890/push/transactions (org.nem.core.connect.HttpMethodClient lambda$sendRequest$2)
2019-10-19 00:40:00.590 WARNING Timer BROADCAST BUFFERED ENTITIES raised exception: java.util.concurrent.CancellationException
java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2265)
        at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.cancelled(HttpMethodClient.java:216)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:157)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionCancelled(DefaultClientExchangeHandlerImpl.java:116)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestCancelled(AbstractClientExchangeHandler.java:357)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$200(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.cancelled(AbstractClientExchangeHandler.java:397)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.cancelled(PoolingNHttpClientConnectionManager.java:295)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$2.cancel(PoolingNHttpClientConnectionManager.java:304)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.cancel(AbstractClientExchangeHandler.java:443)
        at org.apache.http.client.methods.AbstractExecutionAwareRequest.abort(AbstractExecutionAwareRequest.java:90)
        at org.nem.core.connect.HttpMethodClient.lambda$sendRequest$2(HttpMethodClient.java:129)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at org.nem.core.async.SleepFuture$1.run(SleepFuture.java:24)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.util.concurrent.CancellationException
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
        ... 21 more
 (org.nem.core.async.NemAsyncTimerVisitor notifyOperationCompleteExceptionally)
```

```
        at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.cancelled(HttpMethodClient.java:216)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:157)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionCancelled(DefaultClientExchangeHandlerImpl.java:116)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestCancelled(AbstractClientExchangeHandler.java:357)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$200(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.cancelled(AbstractClientExchangeHandler.java:397)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.cancelled(PoolingNHttpClientConnectionManager.java:295)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$2.cancel(PoolingNHttpClientConnectionManager.java:304)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.cancel(AbstractClientExchangeHandler.java:443)
        at org.apache.http.client.methods.AbstractExecutionAwareRequest.abort(AbstractExecutionAwareRequest.java:90)
        at org.nem.core.connect.HttpMethodClient.lambda$sendRequest$2(HttpMethodClient.java:129)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at org.nem.core.async.SleepFuture$1.run(SleepFuture.java:24)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: 
java.util.concurrent.CancellationException
        at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
        at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.cancelled(HttpMethodClient.java:216)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:157)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionCancelled(DefaultClientExchangeHandlerImpl.java:116)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestCancelled(AbstractClientExchangeHandler.java:357)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$200(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.cancelled(AbstractClientExchangeHandler.java:397)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.cancelled(PoolingNHttpClientConnectionManager.java:295)
        at org.apache.http.concurrent.BasicFuture.cancel(BasicFuture.java:150)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$2.cancel(PoolingNHttpClientConnectionManager.java:304)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.cancel(AbstractClientExchangeHandler.java:443)
        at org.apache.http.client.methods.AbstractExecutionAwareRequest.abort(AbstractExecutionAwareRequest.java:90)
        at org.nem.core.connect.HttpMethodClient.lambda$sendRequest$2(HttpMethodClient.java:129)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at org.nem.core.async.SleepFuture$1.run(SleepFuture.java:24)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2019-10-19 08:45:41.326:WARN:oejs.HttpChannel:qtp1340769295-384: Could not send response error 500: javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.util.concurrent.CompletionException: java.util.concurrent.CancellationException
```

**Comment by sweetpotatoz** [comment]
all supernode tests passed, except chain part
