### ISSUE TITLE
Nodes stuck after upgrading to version `v0.6.100`

### ISSUE THREAD

**Issue by jadechip** [NemProject/nem.core#60]
Hi there,
Our nodes keep getting stuck after upgrading to version `v0.6.100` and our users aren't too happy about it.

This is what I see in the logs:
```
2021-12-10 09:04:05.449 WARNING Timer BROADCAST raised exception: org.nem.core.connect.FatalPeerException: Peer returned 500 with error: <�Internal Server Errorrorg.nem.core.connect.InactivePeerException: java.net.ConnectException: Timeout connecting to [/52.73.168.104:7890]֛
                                         >
java.util.concurrent.CompletionException: org.nem.core.connect.FatalPeerException: Peer returned 500 with error: <�Internal Server Errorrorg.nem.core.connect.InactivePeerException: java.net.ConnectException: Timeout connecting to [/52.73.168.104:7890]֛
                 >
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.completed(HttpMethodClient.java:183)
	at org.nem.core.connect.HttpMethodClient$HttpMethodClientFutureCallback.completed(HttpMethodClient.java:173)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.nem.core.connect.FatalPeerException: Peer returned 500 with error: <�Internal Server Errorrorg.nem.core.connect.InactivePeerException: java.net.ConnectException: Timeout connecting to [/52.73.168.104:7890]֛
```

We are using **9Gi** and **14Gi** for the Xms and Xmx memory options respectively.

...and config settings are as follows:

```

nem.shortServerName = Nis
nem.folder = %h
nem.maxThreads = 500

nem.protocol = http
nem.host = 0.0.0.0
nem.httpPort = 7890
nem.httpsPort = 7891
nem.websocketPort = 7778
nem.webContext =
nem.apiContext =
nem.homePath =
nem.shutdownPath = /shutdown

nem.useDosFilter = false

nem.nonAuditedApiPaths = /heartbeat|/status|/chain/height|/chain/score|/chain/last-block|/chain/hashes-from|/push/transaction|/node/ping|/node/info|/node/extended-info|/node/peer-list/active|/account/get|/account/status|/account/unconfirmedTransactions|/account/transfers/all|/account/get/batch

nem.network = mainnet

nis.shouldAutoBoot = true

nis.shouldAutoHarvestOnBoot = false

nis.additionalHarvesterPrivateKeys =

nis.nodeLimit = 5

nis.timeSyncNodeLimit = 10

nis.useBinaryTransport = true

nis.useNetworkTime = false
nis.ipDetectionMode = AutoRequired

nis.unlockedLimit = 4

nis.allowedHarvesterAddresses =

nis.maxTransactions = 10000

nis.maxTransactionsPerBlock = 120

nis.blockGenerationTargetTime = 60
nis.blockChainRewriteLimit = 360

nis.additionalLocalIps =

nis.transactionHashRetentionTime = -1

nis.optionalFeatures = TRANSACTION_HASH_LOOKUP

nis.blockChainFeatures = PROOF_OF_IMPORTANCE|WB_TIME_BASED_VESTING

nis.delayBlockLoading = true

```

**Comment by jadechip** [comment]
@cryptoBeliever I saw your response to another issue, any ideas/clues would be greatly appreciated 🙏

**Comment by Jaguar0625** [comment]
Did you upgrade before or after the Harlock fork?

**Comment by cryptoBeliever** [comment]
@jadechip as @Jaguar0625 mentioned. If you upgraded ~6h = 360 blocks (nis.blockChainRewriteLimit) after fork your node will be not able to catch up with the network.

You can fix that by replacing database:
1) stop node
2) replace database placed in (by default) `<user_home>/nem/nis/data`. You can get pre synced db from https://bob.nem.ninja/nis5_mainnet-latest.h2.db.gz. You should replace with same name.
3) start node

Please let us know if this solved problem.
